title: Basanta Khakurel
email: basantakhakurel@gmail.com
description: Graduate Student at Southeastern Louisiana University

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - research.md
  - CV.md
  - publications.md
